# init_folder:
# 	mkdir -p cmd pkg/config/envs pkg/db pkg/models pkg/pb pkg/services

# init_file:
# 	touch Makefile cmd/main.go pkg/config/envs/dev.env pkg/config/config.go
# 	touch pkg/pb/product.proto pkg/db/db.go pkg/models/stock_decrease_log.go pkg/models/product.go pkg/services/product.go

# proto:

server:
	go run cmd/main.go